import bombCheck from './bombcheck';
import firstClick from './firstClick';
import {combineReducers} from 'redux';

const allReducers = combineReducers({
  bombCheck: bombCheck,
  firstClick: firstClick
});


export default allReducers;

/*
10x10 grid
first click sets 10 bombs
  cover layer of blank buttons
  sublayer of number/blank tile/bomb
    number will be generated by bombs
    blank will be matrix index 0
    Clicking a bomb will remove the entire cover layer
each bomb places a ++ on every element around it in the matric
check for ripple
  logic: if button click is 0 look at surrounding elements uncover all 0s.
  while(ripple === true){
    let surrounding = 
    [
      matrix[e-1][e-1],     topleft  
      matrix[e][e-1],    left   
      matrix[e-1][e],        top 
      matrix[e+1][e-1],     bottomleft
      matrix[e-1][e+1],          topright
      matrix[e+1][e+1],        bottomright
      matrix[e+1][e],             bottom     
      matrix[e][e+1],      right        
    ]
                                                             
  
  }
  stop ripple once you hit a number1

  */